### PR TITLE
use format function

### PR DESCRIPTION
**Pull request by nerdoc**

### CODE REVIEW

**Comment by whart222** [comment]
I'm OK with this change, but I'd like to know what motivates it.

**Comment by nerdoc** [comment]
I'm sorry to make so much noise for a tiny, unimportant change. My Motivation was just: I use pyutilib.component.core as separated lib in my project, and copied the __init__.py and core.py to mine. I changed a few things, and adapted it to Python3 - and, business as usual, backported some things to the original  project ;-)
I know it's not worth a fork and even these lines, but I like polishing...

**Comment by jsiirola** [comment]
My only question is what movitated the change? The current line works in all versions of Python, and the `format` function is slower than `%` in every version of Python.

That said, the current line should have `err` in a tuple as a defensive measure (i.e. `% (err,)`).  As this is not a performance-critical part of code, the change is fine.

**Comment by nerdoc** [comment]
Oh yes, this may be true. This is explained fast: My lack of deep python knowledge. ;-)
I just know the python recommendations, as [PEP-3101](https://www.python.org/dev/peps/pep-3101/) says: *This PEP proposes a new system for built-in string formatting operations, intended as a replacement for the existing '%' string formatting operator.*
But yes, it is faster. I just tested it in a for loop. fastest: Py2 with %, slowest, Py3 with .format().

Don't hesitate to deny this patch... I've learned something again...

**Comment by jsiirola** [comment]
(Belatedly) closing per discussion

**Pull request closed without merging**
