### PR TITLE
[WIP] Removing pyutilib.enum

### PR DESCRIPTION
**Pull request by whart222**
## Summary/Motivation:
Removes the pyutilib.enum package, which has a different license from PyUtilib itself.

## Changes proposed in this PR:
- This simply removes the entire package directory

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by whart222** [comment]
This PR is simple, but it will impact Pyomo.  I'm queueing up the PR, but I don't think we should merge it until Pyomo has been updated to not rely on pyutilib.enum

**Comment by jsiirola** [comment]
Can we pull in enum / enum34 as a deprecation layer?  I know that there are dependent packages that use pyutilib's enum (notably, IDAES).

**Comment by whart222** [comment]
The problem is that the packages are not equivalent.  In particular, pyutilib.enum has an EnumValue type, which Pyomo uses to check whether it's using an enum type.  I don't see an obvious way to recreate that semantics, but I'll explore whether a deprecation warning would work.

**Comment by blnicho** [comment]
Superseded by #101

**Pull request closed without merging**
